Repository hariom20singh/food-delivery-website, pull requests merged in 2022-10, with the labels that each got.

#2 Hacktoberfest 2022
  kadanesalgoinjava00912237.java
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#1 Hacktoberfest2022
  projectstyle.css
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#4 Hacktoberfest 2022
  deleating_of_node0789002.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#6 Food Delivery App Added
  FoodDeliveryApp/client/.gitignore
  FoodDeliveryApp/client/package-lock.json
  FoodDeliveryApp/client/package.json
  FoodDeliveryApp/client/public/favicon.ico
  FoodDeliveryApp/client/public/index.html
  FoodDeliveryApp/client/public/logo192.png
  FoodDeliveryApp/client/public/logo512.png
  FoodDeliveryApp/client/public/manifest.json
  FoodDeliveryApp/client/public/robots.txt
  FoodDeliveryApp/client/src/App.css
  FoodDeliveryApp/client/src/App.js
  FoodDeliveryApp/client/src/App.test.js
  FoodDeliveryApp/client/src/index.css
  FoodDeliveryApp/client/src/index.js
  FoodDeliveryApp/client/src/logo.svg
  FoodDeliveryApp/client/src/reportWebVitals.js
  FoodDeliveryApp/client/src/setupTests.js
  FoodDeliveryApp/server/.gitignore
  FoodDeliveryApp/server/package-lock.json
  FoodDeliveryApp/server/package.json
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#11 Hacktoberfest 2022
  18.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#10 Hacktoberfest 2022
  14.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#9 Hacktoberfest 2022
  11.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#8 Hacktoberfest 2022
  6.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#7 Hacktoberfest 2022
  3.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#14 added files
  FoodDeliveryApp/cpp_codes/ackerman_function.cpp
  FoodDeliveryApp/cpp_codes/ackerman_function.exe
Labels: Hacktoberfest-accepted

#17 Hacktoberfest 2022
  1code102001.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#18 hactoberfest2022
  priorityQueue.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#16 Food-delivery-website
  foodieweb-application/README.md
  foodieweb-application/databases/foodiewebdb.sql
  foodieweb-application/images/blr1.png
  foodieweb-application/images/home.jpg
  foodieweb-application/images/home1.jpg
  foodieweb-application/images/home2.jpg
  foodieweb-application/images/logo.png
  foodieweb-application/images/plt2.png
  foodieweb-application/images/rest1.jpg
  foodieweb-application/images/tq.png
  foodieweb-application/images/wel2.png
  foodieweb-application/sourcecode/adminpanel/adminedit.java
  foodieweb-application/sourcecode/adminpanel/adminlogin.java
  foodieweb-application/sourcecode/userpanel/booked.java
  foodieweb-application/sourcecode/userpanel/confirm.java
  foodieweb-application/sourcecode/userpanel/coupon.java
  foodieweb-application/sourcecode/userpanel/deleteacc.java
  foodieweb-application/sourcecode/userpanel/login.java
  foodieweb-application/sourcecode/userpanel/menu.java
  foodieweb-application/sourcecode/userpanel/rating.java
  foodieweb-application/sourcecode/userpanel/resetpass.java
  foodieweb-application/sourcecode/userpanel/restaurant1.java
  foodieweb-application/sourcecode/userpanel/signup.java
  foodieweb-application/sourcecode/userpanel/view.java
  foodieweb-application/sourcecode/userpanel/welcome.java
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#25 Accepting the three consecutive 1
  ConsecutiveOne.java
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#23 Hactoberfest2022
  insertAtMiddle.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#22 Hactoberfest 2022
  number-pattern.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#21 Hacktoberfest 2022
  02_.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#20 Hacktoberfest 20222
  index.html
Labels: Hacktoberfest-accepted

#19 edgedetection
  edgedetection.py
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#15 HacktoberFest 2022
  Java programs/Basic geometry programs/Area/AreaOfEqTriangle.java
  Java programs/Basic geometry programs/Area/AreaOfRhombus.java
  Java programs/Basic geometry programs/perimeter/PerimeterOfSquare.java
  Java programs/Basic geometry programs/volume/VolumeOfCone.java
  Java programs/Binary search/BinarySearch.java
  Java programs/Binary search/Ceiling.java
  Java programs/Binary search/FirstAndLastPosition.java
  Java programs/EvenOdd.java
  Java programs/IdPass.java
  Java programs/Linear search/EvenDigits.java
  Java programs/Linear search/FindMin.java
  Java programs/Linear search/Main.java
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#26 Stop watch using while loop
  Stop watch using while loop
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#27 hactoberfest 2022
  max_array.cpp
Labels: Hacktoberfest-accepted

#30 Hacktoberfest 2022
  circular_queue.c
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#31 Reversearray
  Recursion Programs/BinarySearch.java
  Recursion Programs/ReverseArray.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#33 Digits Program added
  Recursion Programs/Productofdigits.java
  Recursion Programs/Sumofdigits.java
Labels: Hacktoberfest-accepted

#32 Hectoberfest 22
  fibonacci series.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#34 Hacktoberfest 2022
  Date.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#37 hacktoberfest 2022
  links_and_images.html
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#36 Hactoberfest 2022
  base code.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#38 HAKTOBERFEST 2022
  smaller number array_VEDANT.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#41 HacktoberFest 2022
  Binary_To_Gray_code.cpp
Labels: Hacktoberfest-accepted

#43 hacktoberfest 2022
  op.cpp
Labels: Hacktoberfest-accepted

#40 hacktoberfest2022
  aasdn.c
Labels: Hacktoberfest-accepted

#42 Hactoberfest 2022
  binarTODecimal.cpp
Labels: Hacktoberfest-accepted

#50 hactoberfest2022
  constructor and destructor.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#49 Hactoberfest2022
  PRIYA.XML
Labels: Hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2022

#48 Hacktoberfest 2022
  Calender.py
Labels: Hacktoberfest-accepted

#47 Hacktoberfest-2022
  ExStructArrays.c
Labels: Hacktoberfest-accepted

#45 Hacktoberfest-2022
  bubble.py
Labels: Hacktoberfest-accepted

#44 hacktoberfest2022
  code if else switch .cpp
Labels: Hacktoberfest-accepted

#51 Create FractionalKnapsack.java
  Java programs/FractionalKnapsack.java
Labels: Hacktoberfest-accepted
